"""Add models filters

Revision ID: 74b3cd3106eb
Revises: 
Create Date: 2024-06-28 15:44:31.656021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b3cd3106eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tilted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rotation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cut_information', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('duplicate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_status', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('duplicate')
        batch_op.drop_column('cut_information')
        batch_op.drop_column('rotation')
        batch_op.drop_column('tilted')

    # ### end Alembic commands ###
