# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: converter/converter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'converter/converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63onverter/converter.proto\x12\tconverter\"9\n\x0e\x43onvertRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"!\n\x0f\x43onvertResponse\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x32Q\n\tConverter\x12\x44\n\x0b\x43onvertFile\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'converter.converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=40
  _globals['_CONVERTREQUEST']._serialized_end=97
  _globals['_CONVERTRESPONSE']._serialized_start=99
  _globals['_CONVERTRESPONSE']._serialized_end=132
  _globals['_CONVERTER']._serialized_start=134
  _globals['_CONVERTER']._serialized_end=215
# @@protoc_insertion_point(module_scope)
